name: Dev Actions
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
# Single deploy job since we're just deploying
  deploy:
    name: Dev-Build
    runs-on: [self-hosted, windows, x64]
    steps:
    - run: |
      cd /d B:\Servers\Dev\ForTheMonkeysWebsite\Dev-Branch
      git pull